version: "3.1"
services:
  db:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  app:
    image: "dius/pact-broker"
    env_file:
      - broker.env
    depends_on:
      - db
  nginx:
    image: "nginx:alpine"
    depends_on:
      - app
    volumes:
      - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert:/etc/nginx/cert
    ports:
      - 443:443
      - 80:80
